name: "test"

on: [push, pull_request]

jobs:
  pre-release:
    runs-on: "ubuntu-latest"

    steps:
      - name: Setup ENV
        run: echo "GITHUB_TAG=${GITHUB_REF#*tags/}" >> $GITHUB_ENV

      - name: "Checkout Source Code"
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true
          scope: '@onekeyhq'

      - name: "Install Dependiences"
        run: "yarn && yarn build:libs"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Building"
        run: "cd packages/suite-desktop && yarn copy-files && yarn build:desktop"

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: onekey-extension-${{ github.sha }}
          path: |
            ./packages/suite-desktop/
